### ISSUE TITLE
Large Icon on Plugin Page

### ISSUE THREAD

**Issue by ben-goodman-uk** [bleech/visual-regression-tests#55]
I'm getting a huge icon on the plugin page...

<img width="1607" alt="Screenshot 2023-07-26 at 12 36 22" src="https://github.com/bleech/visual-regression-tests/assets/92758381/0eacbe2e-e997-40ea-a91a-1781e2c9f9ab">

**Comment by timohubois** [comment]
@ben-goodman-uk thank you for creating the issue. We tried to reproduce it with, which was not possible. Do you see any messages within the Browser Console? And do you may use some optimisation plugins to optimise css files?

**Comment by steffenbew** [comment]
Closed due to inactivity.

**Comment by billiemead** [comment]
Same issue! 

![image](https://github.com/bleech/visual-regression-tests/assets/8992422/9fd00e83-1235-4c88-af59-5ab32b781c06)

**Comment by billiemead** [comment]
> Same issue!
> 
> ![image](https://private-user-images.githubusercontent.com/8992422/291396682-9fd00e83-1235-4c88-af59-5ab32b781c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzA0MDAsIm5iZiI6MTcwMjkzMDEwMCwicGF0aCI6Ii84OTkyNDIyLzI5MTM5NjY4Mi05ZmQwMGU4My0xMjM1LTRjODgtYWY1OS01YWIzMmI3ODFjMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMjAwODIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGRmOTE2MzYzMGU1NDRkYjc2MjYzOWIxMGNmYTQ0NjlkOTQ0M2IxZTNhMmUwODFiODk3N2MyYTc0YjA1OGMzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8SsPQOcK1DN_N_eJEYPQFP6ZpeLMN-05nLpuNgLnzfE)

I just opened the icon up in Adobe Illustrator and saved it with Presentations Attributes turned on in SVG settings!

**Comment by steffenbew** [comment]
@billiemead I noticed in your screenshot that the menu items are displayed as an unstyled list (Tests, Alerts, Settings, Upgrade). This in combination with the large logo might indicate that the CSS for the page isn't loading. I would like to understand why that is:
1. Could you please check in the developer tools of your browser if any requests are blocked from loading? There should be a request going to `admin.php?page=vrts`
2. Are you using caching plugins? Those might serve outdated requests.

**Comment by billiemead** [comment]
> @billiemead I noticed in your screenshot that the menu items are displayed as an unstyled list (Tests, Alerts, Settings, Upgrade). This in combination with the large logo might indicate that the CSS for the page isn't loading. I would like to understand why that is:
> 
> 1. Could you please check in the developer tools of your browser if any requests are blocked from loading? There should be a request going to `admin.php?page=vrts`
> 2. Are you using caching plugins? Those might serve outdated requests.

I will check once I install the newest version and get back to you!

**Comment by billiemead** [comment]
Looks okay, here are the request headers:

`Request URL: https://elevartherapeutics-clone.localdev/wp-admin/admin.php?page=vrts
Request Method: GET
Status Code: 
200 OK
Remote Address: 127.0.0.1:443
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-cache, must-revalidate, max-age=0, no-store, private
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 19 Dec 2023 17:23:43 GMT
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Keep-Alive: timeout=5, max=100
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/7.4.32
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.4.32
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: wordpress_sec_938033de276684056d3c4b085c809901=billiemead%7C1704216058%7C6rCC95LN7TH1cnEjnHnj55VYlUWrLsX1RnPkNBSIALT%7C74af69df60c94e154a71c39f3993a69ca3af0de2e5bbdc3d6286661a5e7e3ef1; _ga=GA1.1.1590889043.1702065268; hubspotutk=dc47d0ce00a27b3648ee5c9c46b59744; __hssrc=1; wordpress_test_cookie=WP%20Cookie%20check; _hjSessionUser_3469432=eyJpZCI6IjA0NDAzNWExLTE1MWUtNTExYy1iYTNjLTA5MmFiOTg5MjNkZiIsImNyZWF0ZWQiOjE3MDIwNjUyNjg1MzIsImV4aXN0aW5nIjp0cnVlfQ==; wp_lang=en_US; edgtf-like_17917=17917; cookielawinfo-checkbox-necessary=yes; wp-settings-time-14=1702938052; wp-settings-14=edit_element_vcUIPanelWidth%3D1375%26edit_element_vcUIPanelLeft%3D188px%26edit_element_vcUIPanelTop%3D23px%26panel_vcUIPanelWidth%3D650%26panel_vcUIPanelLeft%3D801px%26panel_vcUIPanelTop%3D73px%26posts_list_mode%3Dlist%26editor%3Dhtml%26libraryContent%3Dbrowse%26mfold%3Do; cookielawinfo-checkbox-functional=yes; cookielawinfo-checkbox-performance=yes; cookielawinfo-checkbox-analytics=yes; cookielawinfo-checkbox-advertisement=yes; cookielawinfo-checkbox-others=yes; viewed_cookie_policy=yes; cli_user_preference=en-cli-yes-checkbox-necessary-yes-checkbox-functional-yes-checkbox-performance-yes-checkbox-analytics-yes-checkbox-advertisement-yes-checkbox-others-yes; CookieLawInfoConsent=eyJ2ZXIiOiIxIiwibmVjZXNzYXJ5IjoidHJ1ZSIsImZ1bmN0aW9uYWwiOiJ0cnVlIiwicGVyZm9ybWFuY2UiOiJ0cnVlIiwiYW5hbHl0aWNzIjoidHJ1ZSIsImFkdmVydGlzZW1lbnQiOiJ0cnVlIiwib3RoZXJzIjoidHJ1ZSJ9; _ga_J9N59KKZLK=GS1.1.1703006456.25.0.1703006456.0.0.0; _hjIncludedInSessionSample_3469432=0; _hjSession_3469432=eyJpZCI6IjJlYjUxMmU1LWNkYWQtNDgxNy1hMzUxLTkwNjVlODRhMDFlMyIsImMiOjE3MDMwMDY0NTY3NzYsInMiOjAsInIiOjAsInNiIjowfQ==; __hstc=94090946.dc47d0ce00a27b3648ee5c9c46b59744.1702065268554.1702937740071.1703006456814.25; __hssc=94090946.1.1703006456814; wordpress_logged_in_938033de276684056d3c4b085c809901=billiemead%7C1704216058%7C6rCC95LN7TH1cnEjnHnj55VYlUWrLsX1RnPkNBSIALT%7C18b7704bb8000a93616209a2e5767c992954275a3e26289c1fc4440cca34d5a8
DNT: 1
Host: elevartherapeutics-clone.localdev
Referer: https://elevartherapeutics-clone.localdev/wp-admin/admin.php?page=vrts-settings
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
sec-ch-ua-mobile: ?1
sec-ch-ua-platform: "Android"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36`

**Comment by billiemead** [comment]
Where is the page CSS that is supposed to be loading? All I see in the assets folder are scss files that need to be built, but I cant find any CSS?

**Comment by steffenbew** [comment]
@billiemead Thank you! Not sure what I was thinking, but I asked you about the wrong URL. 🤦‍♂️  The CSS should be served from the following URL: `/plugins/visual-regression-tests/build/admin.css?ver=`

**Comment by billiemead** [comment]
@steffenbew Ahh! No, its not loading admin.css nor can I find admin.css in the plugin package. Is it created as part of the build process? BC that's currently failing for me (See other issue please).

You may want to distribute the CSS & JS as part of the plugin as I'm not sure how many WordPress users are going to bother building the plugin. Most just expect it to work "out of the box" if you know what I mean?

**Comment by billiemead** [comment]
@steffenbew ok, I am able to run 'npm run start' which builds the CSS and JS assets, and that answers my above question and also takes care of the large icon and the list styling: 

![image](https://github.com/bleech/visual-regression-tests/assets/8992422/865b8af8-9650-4a79-a367-04589c297e11)

**Comment by steffenbew** [comment]
@billiemead Ahh great! Happy to hear it works now for you.

**Comment by domtra** [comment]
@billiemead just one remark for the future: we do not really intend people to install this plugin via composer from github directly, as we do not check in the build files.
if you still want to or need to do that, have a look at https://wpackagist.org/. this wraps all plugins from the wordpress directory with a composer.json. this way, you will only get versions from this plugin that were actually released and they also include all necessary files.
