### ISSUE TITLE
Cannot add new Test VRT 1.7.0

### ISSUE THREAD

**Issue by billiemead** [bleech/visual-regression-tests#59]
WordPress 6.3.1
Host: Pantheon
Repository: GitHub
Local dev environment: Laragon - Apache 2.4.54/MySQL 5.7.40/PHP 7.4

Active Theme: Twenty Twenty-Three
All plugins disabled EXCEPT: VRTs – Visual Regression Tests

On the VRT Settings page, clicking Add New button does nothing. And no errors are shown in Console (the two errors shown in video are from Loom, the screen recording app)

https://www.loom.com/share/6aa763dbb5d446f8abc5537eea98a418?sid=96cd1fdd-fc52-4173-921c-ae05d7cf921a

All and Running both show (1) Test but none have been created yet
![Settings page](https://billiemead.com/files/vrt-tests-settings.png)

![Themes](https://billiemead.com/files/active_theme.png)
![Plugins](https://billiemead.com/files/active_plugins.png)

**Comment by harunbleech** [comment]
Hi @billiemead, the version 1.7.0 wasn't ready for public release yesterday as we needed also to adjust our service to support some features first. 

The 1.7.0 is ready now to be used and now it's also published on wordpress.org.

**Comment by billiemead** [comment]
Still having issues. `npm run build` is failing (will post details). Also, https://bleech-vrts-app.blee.ch/api/v1/ is giving a 404 error

**Comment by billiemead** [comment]
@steffenbew ok.. the tests are in the MySQL database, in the `vrts_tests` table. But we use a table prefix so its actually `wpi5_vrts_tests`. And in the file  `includes/tables/class-tests-table.php` line 8, it doesn't look like you accounted for table prefixes. So I think that's why they are not displaying. 

This can be set in `wp-config.php` as `$table_prefix`... but both WP Engine and Pantheon use a file `wp-config-local.php` so FYI, it can be set there as well.

**Comment by domtra** [comment]
hey @billiemead. unfortunately, it is really hard to make sense of all of this.
could you please try to upgrade to v1.7.1 of the plugin? best use either the update functionality in wp-admin, or if through composer via https://wpackagist.org/.
if things still do not work after that, please uninstall the plugin via wp-admin. if you cannot do this, i will provide you with a couple of db queries you can alternatively try out.

**Comment by billiemead** [comment]
@domtra the error was because the table name was changed to base_screenshot_date during one of the version updates and the ALTER table statement didn't work, so I just renamed the table in MySQL and the error is gone.
